financial_analysis_proj/financial_analysis_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finertia.urls')),  # Include the finertia app URLs
]

financial_analysis_proj/finertia/urls.py
from django.urls import path, re_path
from .views import SignupView, LoginView, logout, dashboard, insights, desktop1_api
from django.views.generic import TemplateView

urlpatterns = [
    path('accounts/signup/', SignupView.as_view(), name='signup'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
    # path('', dashboard, name='dashboard'),
    path('insights', insights, name='insights'),
    # re_path(r'^.*', serve_react_app, name='react_app'),
    path('', TemplateView.as_view(template_name='home/index.html')),
    # path('api/desktop1', desktop1_api, name='desktop1_api')
]

financial_analysis_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finertia.urls')),  # Include the finertia app URLs
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

finertia/urls.py
from django.urls import path
from finertia import views
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from .views import SignupView, LoginView, logout, home, dashboard, analytics, insights, payments,financial_form_view,transfer_success,bill_payment_success

app_name = 'finertia'

urlpatterns = [
    path('accounts/signup/', SignupView.as_view(), name='signup'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
    path('', views.home, name='home'),
    path('dashboard', dashboard, name='dashboard'),
     path('analytics', financial_form_view, name='analytics'),
    path('insights', insights, name='insights'),
    path('payments', payments, name='payments'),
    path('forms',financial_form_view,name='financial_form_view'),
    path('password_reset/', PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('transfer_success/', transfer_success, name='transfer_success'),
    path('bill_payment_success/', bill_payment_success, name='bill_payment_success'),

]

financial_analysis_proj/finertia/models.py
from django.db import models

# Create your models here.

finertia/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission, User
from django.db import models
from django.conf import settings  # For accessing the custom user model


class AllTransactions(models.Model):
    date = models.DateTimeField()
    mode = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    subcategory = models.CharField(max_length=100)
    note = models.TextField(blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    income_expense = models.CharField(max_length=20)
    currency = models.CharField(max_length=3)

    def __str__(self):
        return f"{self.date} - {self.category} - {self.amount} {self.currency}"


class UserData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    transactions = models.ManyToManyField(AllTransactions)

    def __str__(self):
        return self.user.username


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    mobile_number = models.CharField(max_length=15, blank=True)
    groups = models.ManyToManyField(Group, related_name='custom_user_set', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_set_permissions', blank=True)

    class Meta:
        db_table = 'custom_user'

    def __str__(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    additional_field1 = models.CharField(max_length=255, blank=True)
    additional_field2 = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.user.username

class Card(AllTransactions):
    card_number = models.IntegerField(max_length=16)
    cvv_number = models.IntegerField(max_length=3)

    def __str__(self):
        return f"{self.card_number} - {self.cvv_number}"

financial_analysis_proj/finertia/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views import View

class SignupView(View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'registration/signup.html', {'form': form})

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dashboard')
        return render(request, 'registration/signup.html', {'form': form})

class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'registration/login.html', {'form': form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username=form.cleaned_data.get('username'),
                password=form.cleaned_data.get('password')
            )
            if user is not None:
                login(request, user)
                return redirect('dashboard')
        return render(request, 'registration/login.html', {'form': form})

@login_required
def dashboard(request):
    return render(request, 'dashboard.html')

def logout(request):
    auth_logout(request)
    return render(request,'registration/login.html')


def insights(request):
    return render(request,'dashboard.html')


def desktop1_api(request):
    data = {
        "ourServices": "Our Services",
        "products": [
            {"name": "Product"},
            {"name": "Manage your Finances"},
            {"name": "Savings Schemes"},
            {"name": "Financial Insights"}
        ],
        "navItems": ["Home", "Product", "Banking", "Login"],
        "footerText": "Follow us to know more",
        "contactUs": "Contact Us",
        "description": "Financial wellness is a way of effectively managing your finances. Not knowing how to deal with your finances can lead to major stress, anxiety or depression. Finance plays a substantial role in your daily wellness and well-being."
    }
    return JsonResponse(data)

finertia/views.py
from django.utils import timezone

from django.contrib.auth import authenticate, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import FinancialForm,BillPaymentForm,TransferForm
from .MLmodel import classify_financial_status_and_suggest_plan
import pandas as pd

# class SignupView(View):
#     def get(self, request):
#         form = UserCreationForm()
#         return render(request, 'registration/signup.html', {'form': form})
#
#     def post(self, request):
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             return redirect('finertia:dashboard')
#         return render(request, 'registration/signup.html', {'form': form})


from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.views import View
from .models import UserData, AllTransactions
import random
from django.db.models import Sum, DecimalField
from django.db.models.functions import Coalesce
import json
from django.core.serializers.json import DjangoJSONEncoder
from django import forms
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    mobile_number = forms.CharField(max_length=15, required=True)

    class Meta:
        model = CustomUser
        fields = ("username", "first_name", "last_name", "email", "mobile_number", "password1", "password2")


class SignupView(View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'registration/signup.html', {'form': form})

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            print("Form is valid")
            user = form.save()
            login(request, user)
            # user = form.save(commit=False)  # Get the unsaved CustomUser instance
            # user.set_password(form.cleaned_data['password'])
            # user.save()
            print('user: ',user)
            user_data = UserData.objects.create(user=user)

            # Get 15 random transactions
            all_transactions = list(AllTransactions.objects.all())
            random_transactions = random.sample(all_transactions, 15)

            # Add transactions to user_data
            user_data.transactions.add(*random_transactions)
            return redirect('finertia:login')
        else:
            print("Form is not valid")
            print(form.errors)
        return render(request, 'registration/signup.html', {'form': form})


class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'registration/login.html', {'form': form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username=form.cleaned_data.get('username'),
                password=form.cleaned_data.get('password')
            )
            if user is not None:
                print("Logged in successfully")
                login(request, user)
                return redirect('finertia:dashboard')
            else:
                # Add an error if authentication fails
                form.add_error(None, "Invalid username or password")
        else:
            # Handle form errors (e.g., empty fields)
            form.add_error(None, "Please correct the errors below.")
        print("Login failed")
        return render(request, 'registration/login.html', {'form': form, })


def home(request):
    return render(request, 'home.html')


# @login_required
# def dashboard(request):
#     user_data = UserData.objects.get(user=request.user)
#     user_transactions = user_data.transactions.all()
#     context = {
#         'transactions': user_transactions,
#         'username': request.user.username  # Add this line
#     }
#     return render(request, 'dashboard.html', context)

@login_required
def dashboard(request):
    user_data = UserData.objects.get(user=request.user)
    user_transactions = user_data.transactions.all()

    # Calculate spending by category
    category_spending = user_transactions.filter(income_expense='Expense').values('category').annotate(
        total=Coalesce(Sum('amount', output_field=DecimalField()), 0, output_field=DecimalField())
    ).order_by('-total')

    # Prepare data for the chart
    categories = [item['category'] for item in category_spending]
    amounts = [float(item['total']) for item in category_spending]

    context = {
        'transactions': user_transactions,
        'username': request.user.username,
        'categories_json': json.dumps(categories, cls=DjangoJSONEncoder),
        'amounts_json': json.dumps(amounts, cls=DjangoJSONEncoder),
    }
    return render(request, 'dashboard.html', context)


@login_required
def analytics(request):
    return render(request, 'analytics.html')


@login_required
def insights(request):
    return render(request, 'insights.html')




@login_required
def logout(request):
    if request.method == 'GET':
        auth_logout(request)
        return render(request, 'registration/login.html')

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username=form.cleaned_data.get('username'),
                password=form.cleaned_data.get('password')
            )
            if user is not None:
                login(request, user)
                return redirect('finertia:dashboard')
        return render(request, 'registration/login.html', {'form': form})


@login_required
def financial_form_view(request):
    if request.method == 'POST':
        form = FinancialForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            stability, loan_eligibility, suggested_loan_amount, plan_text,suggested_loan_term = classify_financial_status_and_suggest_plan(
                form_data)
            return render(request, 'insights.html', {
                'stability': stability,
                'loan_eligibility': loan_eligibility,
                'suggested_loan_amount': suggested_loan_amount,
                'plan_text': plan_text,
                'suggested_loan_term': suggested_loan_term,
            })
    else:
        form = FinancialForm()
    return render(request, 'analytics.html', {'form': form})


def payments(request):
    transfer_form = TransferForm()
    bill_payment_form = BillPaymentForm()

    if request.method == 'POST':
        if 'transfer' in request.POST:
            transfer_form = TransferForm(request.POST)
            if transfer_form.is_valid():
                to_account = transfer_form.cleaned_data['to_account']
                amount = transfer_form.cleaned_data['amount']
                note = transfer_form.cleaned_data['note']

                transaction = AllTransactions.objects.create(
                    date=timezone.now(),
                    mode='Transfer',
                    category='Transfer',
                    subcategory='To Account',
                    note=note,
                    amount=amount,
                    income_expense='expense',
                    currency='CAD'
                )
                print(request.user)
                user_data = UserData.objects.get(user=request.user)
                print(user_data)
                print('user trnsact')
                user_data.transactions.add(transaction)
                return redirect('finertia:transfer_success')
        # elif 'bill_payment' in request.POST:
        #     bill_payment_form = BillPaymentForm(request.POST)
        #     if bill_payment_form.is_valid():
        #         bill_payment = bill_payment_form.save(commit=False)
        #         bill_payment.mode = 'Bill Payment'
        #         bill_payment.category = 'Bill'
        #         bill_payment.subcategory = 'Utility'
        #         bill_payment.income_expense = 'expense'
        #         bill_payment.save()
        #
        #         user_data = UserData.objects.get(user=request.user)
        #         user_data.transactions.add(bill_payment)
        #         return redirect('bill_payment_success')
        elif 'bill_payment' in request.POST:
            bill_payment_form = BillPaymentForm(request.POST)
            if bill_payment_form.is_valid():
                bill_payment = bill_payment_form.save(commit=False)
                bill_payment.mode = 'Bill Payment'
                bill_payment.category = 'Bill'
                bill_payment.income_expense = 'expense'
                bill_payment.save()

                user_data = UserData.objects.get(user=request.user)
                user_data.transactions.add(bill_payment)
                return redirect('finertia:bill_payment_success')

    return render(request, 'payments.html', {
        'transfer_form': transfer_form,
        'bill_payment_form': bill_payment_form,
    })


def transfer_success(request):
    return render(request, 'transfer_success.html')


def bill_payment_success(request):
    return render(request, 'bill_payment_success.html')

finertia/templates/bill_payment_success.html
{% extends 'base1.html' %}
{% load static %}
{% block body_block %}
	{% block content %}
    <h2>Bill Payment Successful!</h2>
    <a href="{% url 'finertia:payments' %}">
        <button style="background-color: rgb(42, 159, 163);">Pay another bill</button>
    </a>
{% endblock %}
{% endblock %}

finertia/templates/insights.html
{#{% load static %}#}
{#<!doctype html>#}
{#<html lang="en">#}
{#  <head>#}
{#    <meta charset="UTF-8" />#}
{#    <meta http-equiv="X-UA-Compatible" content="IE=Edge">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#    <title>Desktop - 1</title>#}
{#    <link rel="preconnect" href="https://fonts.googleapis.com">#}
{#    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>#}
{#    <link href="https://fonts.googleapis.com/css2?family=Bungee+Spice:wght@400&display=swap" rel="stylesheet">#}
{#    <link rel="preconnect" href="https://fonts.googleapis.com">#}
{#    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>#}
{#    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap" rel="stylesheet">#}
{#    <link rel="preconnect" href="https://fonts.googleapis.com">#}
{#    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>#}
{#    <link href="https://fonts.googleapis.com/css2?family=Bungee+Color:wght@400&display=swap" rel="stylesheet">#}
{#    <link rel="stylesheet" href="../static/finertia/css/insights_css.css" />#}
{#  </head>#}
{#  <body>#}
{#    <div class="desktop-1">#}
{#      <div class="container">#}
{#          <div class="d-flex flex-column justify-content-center align-content-center w-100">#}
{#          <img src="{% static 'finertia/assets/images/stock_cake_digital_finance_hub_17182170571.jpeg' %}" alt = "load image" class="d-block w-100">#}
{#          <img src="../static/finertia/assets/analtics_insights_payments/images/finertia_transparent_1.png" style="height: 250px; width: 250px; margin-right: 1300px">#}
{##}
{#        <div class="frame-19" >#}
{#                 <div class="frame-17" >#}
{#                <span class="login">#}
{#                  <a class="navbar-brand"  style="color:white; text-decoration: none;" href="{% url 'finertia:logout' %}">Logout</a>#}
{#                </span>#}
{#               </div>#}
{#                 <div class="home">#}
{#                     <a class="navbar-brand" style="color:white; text-decoration: none;" href="{% url 'finertia:home' %}">Home</a>#}
{#                </div>#}
{#                 <img src="../static/finertia/assets/analtics_insights_payments/images/finertia_transparent_1.png" style="height: 250px; width: 250px; margin-right: 1300px">#}
{#        </div>#}
{#              </div>#}
{##}
{##}
{#        <div class="sidebar">#}
{#          <div class="manage">MANAGE</div>#}
{#          <div class="menu-item">#}
{#            <img src="../static/finertia/assets/analtics_insights_payments/vectors/vector_2_x2.svg" alt="Dashboard Icon" />#}
{#            <span><a class="navbar-brand"  style="color:white; text-decoration: none;" href="{% url 'finertia:dashboard' %}">Dashboard</a></span>#}
{#          </div>#}
{#          <div class="menu-item">#}
{#            <img src="../static/finertia/assets/analtics_insights_payments/vectors/vector_17_x2.svg" alt="Analytics Icon" />#}
{#              <span><a class="navbar-brand"  style="color:white; text-decoration: none;" href="{% url 'finertia:analytics' %}">Analytics</a></span>#}
{#          </div>#}
{#          <div class="menu-item">#}
{#            <img src="../static/finertia/assets/analtics_insights_payments/vectors/vector_31_x2.svg" alt="Insights Icon" />#}
{#              <span><a class="navbar-brand"  style="color:white; text-decoration: none;" href="{% url 'finertia:insights' %}">Insights</a></span>#}
{#          </div>#}
{##}
{#          <div class="preferences">PREFERENCES</div>#}
{##}
{#          <div class="menu-item">#}
{#            <img src="../static/finertia/assets/analtics_insights_payments/vectors/vector_34_x2.svg" alt="Payments Icon" />#}
{#              <span><a class="navbar-brand"  style="color:white; text-decoration: none;" href="{% url 'finertia:payments' %}">Payments</a></span>#}
{#          </div>#}
{#        </div>#}
{#            <div class="frame-8">#}
{#              <div class="frame-81">#}
{#                <span class="step-2">#}
{#                Step 2#}
{#                </span>#}
{#                <span class="container-2">#}
{#                ”#}
{#                </span>#}
{#              </div>#}
{#              <div class="frame-10">#}
{#                <span class="step-4">#}
{#                Step 4#}
{#                </span>#}
{#                <span class="container-4">#}
{#                ”#}
{#                </span>#}
{#              </div>#}
{#              <div class="frame-12">#}
{#                <span class="step-6">#}
{#                Step 6#}
{#                </span>#}
{#                <span class="container-6">#}
{#                ”#}
{#                </span>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#          <div class="frame-7">#}
{#            <span class="step-1">#}
{#            -Step 1#}
{#            </span>#}
{#            <span class="container-1">#}
{#            ”#}
{#            </span>#}
{#          </div>#}
{#          <div class="frame-9">#}
{#            <span class="step-3">#}
{#            -Step 3#}
{#            </span>#}
{#            <span class="container-3">#}
{#            ”#}
{#            </span>#}
{#          </div>#}
{#          <div class="frame-11">#}
{#            <span class="step-5">#}
{#            Step 5#}
{#            </span>#}
{#            <span class="container-5">#}
{#            ”#}
{#            </span>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#      <div class="stock-cake-digital-finance-hub-17182170571">#}
{#      </div>#}
{#      <div class="frame-19">#}
{#        <div class="container-11">#}
{#          <span class="home">#}
{#          Home#}
{#          </span>#}
{#          <span class="product">#}
{#          Product#}
{#          </span>#}
{#        </div>#}
{#        <div class="banking">#}
{#        Banking#}
{#        </div>#}
{#        <div class="frame-17">#}
{#          <div class="container">#}
{#          </div>#}
{#          <div class="container-1">#}
{#            <div class="user">#}
{#            User#}
{#            </div>#}
{#            <span class="sampleusergmail-com">#}
{#            sampleuser@gmail.com#}
{#            </span>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{#  </body>#}
{#</html>#}



<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Desktop - 1</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Color:wght@400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Spice:wght@400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'finertia/css/analytics_css.css' %}" />
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap');

        .sidebar {
            margin-top: 20px;
            height: 2200px;
            padding: 20px;
            color: white;
            font-family: 'Roboto', sans-serif;
        }

        .manage, .preferences {
            font-size: 20px;
            font-weight: 700;
            margin-bottom: 20px;
        }

        .menu-item {
            display: flex;
            align-items: center;
            margin-bottom: 15px;
        }

        .menu-item img {
            margin-right: 10px;
        }

        .navbar-brand {
            color: white;
            text-decoration: none;
            font-size: 20px;
            font-weight: 500;
            transition: color 0.3s ease, text-shadow 0.3s ease, transform 0.3s ease;
        }

        .navbar-brand:hover {
            color: #ffcc00;
            text-shadow: 0 0 10px #ffcc00;
            text-decoration: underline;
            transform: scale(1.1);
        }

        .financial-form {
            background-color: #2a2a2a; /* Slightly lighter color than black */
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            max-width: 1200px; /* Increased width of the form */
            margin: 0 auto;
            color: #fff;
        }

        .financial-form h1 {
            text-align: center;
            margin-bottom: 20px;
            color: rgb(42, 159, 163);;
        }

        .financial-form label {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
            color: rgb(42, 159, 163); /* Attractive and eye-catching color */
        }

        .financial-form input,
        .financial-form select,
        .financial-form textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .financial-form .inline-radio {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
        }

        .financial-form .inline-radio label {
            margin-right: 20px;
        }

        .financial-form button {
            width: 100%;
            padding: 10px;
            background-color: rgb(42, 159, 163); /* Attractive and eye-catching color */
            border: none;
            border-radius: 5px;
            font-weight: bold;
            cursor: pointer;
            color: #2a2a2a;
        }

       .financial-form:hover {
    background-color: #333; /* Slightly lighter color on hover */
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2); /* Deeper shadow on hover */
}

       p{
           color: white;
           font-family: "Berlin Sans FB", sans-serif;
           font-weight: bolder;
       }

    </style>
</head>
<body>
    <div class="desktop-1">
        <div class="container">
            <div class="frame-19">
                <div class="frame-17">
                    <span class="login">
                        <a class="navbar-brand" style="color:white; text-decoration: none;" href="{% url 'finertia:logout' %}">Logout</a>
                    </span>
                </div>
                <div class="home">
                    <a class="navbar-brand justify-content-between" style="color:white; text-decoration: none;" href="{% url 'finertia:home' %}">Home</a>
                </div>
                <img src="{% static 'finertia/assets/analtics_insights_payments/images/finertia_transparent_1.png' %}" style="height: 250px; width: 250px; margin-right: 1300px">
            </div>

            <div class="sidebar">
                <div class="manage">MANAGE</div>
                <div class="menu-item">
                    <img src="{% static 'finertia/assets/analtics_insights_payments/vectors/vector_2_x2.svg' %}" alt="Dashboard Icon" />
                    <span><a class="navbar-brand" style="color:white; text-decoration: none;" href="{% url 'finertia:dashboard' %}">Dashboard</a></span>
                </div>
                <div class="menu-item">
                    <img src="{% static 'finertia/assets/analtics_insights_payments/vectors/vector_17_x2.svg' %}" alt="Analytics Icon" />
                    <span><a class="navbar-brand" style="color:white; text-decoration: none;" href="{% url 'finertia:analytics' %}">Analytics</a></span>
                </div>
                <div class="menu-item">
                    <img src="{% static 'finertia/assets/analtics_insights_payments/vectors/vector_31_x2.svg' %}" alt="Insights Icon" />
                    <span><a class="navbar-brand" style="color:white; text-decoration: none;" href="{% url 'finertia:insights' %}">Insights</a></span>
                </div>

                <div class="preferences">PREFERENCES</div>

                <div class="menu-item">
                    <img src="{% static 'finertia/assets/analtics_insights_payments/vectors/vector_34_x2.svg' %}" alt="Payments Icon" />
                    <span><a class="navbar-brand" style="color:white; text-decoration: none;" href="{% url 'finertia:payments' %}">Payments</a></span>
                </div>
            </div>

            <div class="main-content">
                <div class="transactions">
                    <!-- Financial Form Section -->
                    <div class="financial-form">
        <h1>Financial Analysis Results</h1>
        <p style="color: white"><strong style="color: #00BD9D">Financial Status:</strong> {{ stability }}</p>
        <p style="color: white"><strong style="color: #00BD9D">Loan Eligibility:</strong> {{ loan_eligibility }}</p>

    {% if loan_eligibility == 'Eligible' %}
        <p style="color: white"><strong style="color: #00BD9D">Suggested Loan Amount:</strong> {{ suggested_loan_amount }}</p>
        <p style="color: white"><strong style="color: #00BD9D">Suggested Loan Term:</strong> {{ suggested_loan_term }} years</p>
    {% endif %}
    <h2>Personalized Financial Plan:</h2>
                    <div class="card-body" style="width: 500px">
                        <pre style="font-weight: bolder;width: 600px">{{ plan_text }}</pre></div>
    <button onclick="window.location.href='{% url 'finertia:financial_form_view' %}'">Back to Form</button>
</div>
                    <!-- End of Financial Form Section -->
                </div>
            </div>
        </div>
    </div>
</body>
</html>

finertia/templates/transfer_success.html
{% extends 'base1.html' %}
{% load static %}

{% block body_block %}
	{% block content %}
		<h2>Transfer Successful!</h2>
        <a href="{% url 'finertia:payments' %}">
            <button style="background-color: rgb(42, 159, 163);">Make another transfer</button></a>
	{% endblock %}
{% endblock %}